Add option to disable recursive traversal of symbolic target
SuperCuber/dotter pull request #89
Opened 2021-11-14 00:08 UTC by cjgu

## What
Implement a way to optionally disable recursive traversal of symbolic target as mentioned in https://github.com/SuperCuber/dotter/issues/67#issuecomment-851022618 and https://github.com/SuperCuber/dotter/issues/74#issuecomment-864546939

Allows to symlink the directory instead of each file inside the directory:
```
vim = { target="~/.vim", type="symbolic", recursive=false }
```

## Implementation details 
I'm not too happy with the destructing of the SymbilicTarget and would be happy to take suggestion on improving it.

2021-11-14 09:22 UTC, SuperCuber requested changes
In addition to that I'm worried about edge cases like changing from recursive to non recursive and then deploying or changing from `{ target="a", recursive=false }` to `{ target="a/foo" }` - gotta make sure the code handles those properly, maybe even add unit tests for these cases.

2021-11-14 09:22 UTC, SuperCuber commented on src/config.rs
> +    pub recursive: Option<bool>,
This should probably be a `bool`, and by default deserialize to `true` when it's missing. Look into `serde field attributes` to make that happen

2021-11-14 09:22 UTC, SuperCuber commented on src/config.rs
> +    } else if let FileTarget::Symbolic(SymbolicTarget{target:_, owner:_, condition: _, recursive: Some(false)}) = target {
This can be `if let FileTarget::Symbolic(SymbolicTarget { recursive: false, .. })` with the previous change

2021-11-14 09:25 UTC, SuperCuber commented
Depending on whether it "just works" with the edge cases I mentioned this PR could be basically done or really complex, fingers crossed 🤞

2021-11-14 22:18 UTC, cjgu commented
Thank you for the quick review! I'll try testing those edge cases and try writing some tests for them, and do the other adjustments.

2022-03-07 03:19 UTC, dead10ck commented
@cjgu are you still planning on continuing this work?

2022-03-12 13:05 UTC, cjgu commented
Hey! Sorry for lack of updates here.

I did a bit of testing on how to implement it to support toggling the `recursive` on a directory but it was quite complicated and my need of this changed a bit. If you want to take this further you are very welcome to do so.

2022-04-02 08:30 UTC, closed without merging

2022-04-02 08:30 UTC, SuperCuber commented
Closed via #94